fix(#345): Find all problems
dotenv-linter/dotenv-linter pull request #348
Opened 2020-12-04 14:20 UTC by vbrandl

This fixes the problems described in #345.

I had to change some tests to make them pass again. Since this is my first commit, I am not quite sure if every change I made is acceptable so this will need some review.

#### ✔ Checklist:

- [x] Commit messages have been written in [Conventional Commits](https://www.conventionalcommits.org) format;
- [ ] This PR has been added to [CHANGELOG.md](https://github.com/dotenv-linter/dotenv-linter/blob/master/CHANGELOG.md) (at the top of the list);
- [x] Tests for the changes have been added (for bug fixes / features);
- [ ] Docs have been added / updated on the [dotenv-linter.github.io](https://github.com/dotenv-linter/dotenv-linter.github.io) (for bug fixes / features).

2020-12-04 19:14 UTC, mgrachev requested changes
@vbrandl 👋 Thank you for your contribution! 🚀

I have left a comment. Please take a look at it 👀

2020-12-05 10:46 UTC, vbrandl commented
I added a testcase for `export FOOBAR` and had to change the parameter used to generate the error message. Also `get_key` will now always return the stripped `str`.

2020-12-05 11:35 UTC, mgrachev approved these changes

2020-12-05 11:35 UTC, merged

2020-12-05 11:38 UTC, mgrachev commented
@vbrandl Thanks a lot! ⚡️